import React, { useState, useEffect } from "react";
import axios from "axios";
import { Plus, Send, X, Edit2, AlertCircle, CheckCircle2, MapPin, Sparkles, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function BlogForm({ onSubmit, initialData, onCancel }) {
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    skills: "",
    tags: "",
    location: "",
  });
  const [loading, setLoading] = useState(false);
  const [msg, setMsg] = useState({ type: "", text: "" });

  const [aiLoading, setAiLoading] = useState(false);
  const [aiInput, setAiInput] = useState({ topic: "", details: "" });

  const BASE_API = (import.meta.env.VITE_API_URL || "http://localhost:5000/api/auth").replace("/api/auth", "/api");

  useEffect(() => {
    if (initialData) {
      setFormData({
        title: initialData.title || "",
        description: initialData.description || "",
        skills: Array.isArray(initialData.skills) ? initialData.skills.join(", ") : "",
        tags: Array.isArray(initialData.tags) ? initialData.tags.join(", ") : "",
        location: initialData.location || initialData.region || "",
      });
    } else {
      setFormData({ title: "", description: "", skills: "", tags: "", location: "" });
    }
  }, [initialData]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.title || !formData.description || !formData.skills) {
      setMsg({ type: "error", text: "Please fill all required fields" });
      return;
    }

    setLoading(true);
    setMsg({ type: "", text: "" });
    try {
      await onSubmit(formData, initialData?._id);
      setMsg({ type: "success", text: initialData ? "Blog updated!" : "Blog created!" });
      if (!initialData) setFormData({ title: "", description: "", skills: "", tags: "", location: "" });
      setTimeout(() => setMsg({ type: "", text: "" }), 3000);
    } catch (err) {
      setMsg({ type: "error", text: err.response?.data?.message || "Something went wrong" });
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    if (!aiInput.topic) {
      setMsg({ type: "error", text: "A topic is required for AI generation" });
      return;
    }

    setAiLoading(true);
    setMsg({ type: "", text: "" });
    try {
      const token = localStorage.getItem("token");
      const res = await axios.post(
        `${BASE_API}/blogs/generate`,
        { topic: aiInput.topic, details: aiInput.details },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      
      const generated = res.data.data;
      setFormData({
        ...formData,
        title: generated.title || formData.title,
        description: generated.description || formData.description,
        skills: generated.skills ? generated.skills.join(", ") : formData.skills,
        tags: generated.tags ? generated.tags.join(", ") : formData.tags,
      });

      setMsg({ type: "success", text: "Success! Content generated by AI." });
    } catch (err) {
      setMsg({ type: "error", text: err.response?.data?.message || err.message || "AI Generation failed" });
    } finally {
      setAiLoading(false);
    }
  };

  const inputClass = "w-full px-3 py-2.5 bg-white/[0.03] border border-white/[0.08] rounded-xl text-sm text-white placeholder-white/15 font-medium outline-none focus:border-violet-500/50 focus:bg-white/[0.05] transition-all";

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="bg-[#11111a] border border-white/[0.08] rounded-2xl p-5 shadow-2xl overflow-hidden relative"
    >
      <div className="flex items-center justify-between mb-5 pb-3 border-b border-white/[0.04]">
        <div className="flex items-center gap-3">
          <div className={`w-9 h-9 rounded-xl flex items-center justify-center ${initialData ? 'bg-amber-500/20 text-amber-400' : 'bg-violet-500/20 text-violet-400'}`}>
            {initialData ? <Edit2 size={18} /> : <Plus size={18} />}
          </div>
          <div>
            <h2 className="text-lg font-black text-white tracking-tight">
              {initialData ? "Update Post" : "Create Blog"}
            </h2>
            <p className="text-[10px] text-white/30 uppercase tracking-widest font-bold mt-0.5">
              {initialData ? "Refining content" : "Share with the community"}
            </p>
          </div>
        </div>
        {initialData && (
          <button onClick={onCancel} className="p-1.5 rounded-lg bg-white/[0.04] text-white/50 hover:bg-white/10 hover:text-white transition-all border border-white/[0.06]">
            <X size={16} />
          </button>
        )}
      </div>

      <AnimatePresence mode="wait">
        {msg.text && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className={`flex items-center gap-2 px-3 py-2.5 mb-4 rounded-xl border text-xs ${
              msg.type === "error"
                ? "bg-red-500/10 border-red-500/20 text-red-400"
                : "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
            } font-medium`}
          >
            {msg.type === "error" ? <AlertCircle size={14} /> : <CheckCircle2 size={14} />}
            {msg.text}
          </motion.div>
        )}
      </AnimatePresence>

      {/* AI GENERATOR SECTION (Only show when creating a new blog) */}
      {!initialData && (
        <div className="mb-6 p-4 rounded-xl bg-gradient-to-r from-violet-500/10 to-fuchsia-500/10 border border-violet-500/20 shadow-inner">
          <div className="flex items-center gap-2 mb-3">
            <Sparkles size={16} className="text-violet-400" />
            <h3 className="text-sm font-bold text-white tracking-tight">Generate Blog with AI</h3>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
            <input 
              type="text" 
              placeholder="Topic (e.g. Electrician Skills in 2025) *" 
              value={aiInput.topic} 
              onChange={(e) => setAiInput({ ...aiInput, topic: e.target.value })} 
              className={inputClass} 
              disabled={aiLoading}
            />
            <input 
              type="text" 
              placeholder="Additional details (optional)" 
              value={aiInput.details} 
              onChange={(e) => setAiInput({ ...aiInput, details: e.target.value })} 
              className={inputClass} 
              disabled={aiLoading}
            />
          </div>
          
          <button
            type="button"
            onClick={handleGenerate}
            disabled={aiLoading || !aiInput.topic}
            className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl font-bold text-xs text-white bg-white/10 hover:bg-white/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed border border-white/10"
          >
            {aiLoading ? (
               <div className="flex items-center gap-2">
                 <Loader2 size={14} className="animate-spin text-violet-300" />
                 <span>Writing content...</span>
               </div>
            ) : (
              <>
                Generate Blog
                <Sparkles size={12} />
              </>
            )}
          </button>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-3.5">
        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-white/30 uppercase tracking-widest pl-0.5">Title *</label>
            <input type="text" placeholder="e.g., Intro to Digital Literacy" value={formData.title} onChange={(e) => setFormData({ ...formData, title: e.target.value })} className={inputClass} />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-white/30 uppercase tracking-widest pl-0.5 flex items-center gap-1"><MapPin size={10} /> Location</label>
            <input type="text" placeholder="e.g., Mumbai" value={formData.location} onChange={(e) => setFormData({ ...formData, location: e.target.value })} className={inputClass} />
          </div>
        </div>

        <div className="space-y-1">
          <label className="text-[10px] font-bold text-white/30 uppercase tracking-widest pl-0.5">Description *</label>
          <textarea rows="2" placeholder="Describe the skills or outcomes..." value={formData.description} onChange={(e) => setFormData({ ...formData, description: e.target.value })} className={`${inputClass} resize-none`} />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-white/30 uppercase tracking-widest pl-0.5">Skills (comma separated) *</label>
            <input type="text" placeholder="e.g., communication, python" value={formData.skills} onChange={(e) => setFormData({ ...formData, skills: e.target.value })} className={inputClass} />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-white/30 uppercase tracking-widest pl-0.5">Tags (optional)</label>
            <input type="text" placeholder="e.g., student, tech, design" value={formData.tags} onChange={(e) => setFormData({ ...formData, tags: e.target.value })} className={inputClass} />
          </div>
        </div>

        <div className="pt-2">
          <button
            type="submit"
            disabled={loading}
            className={`w-full group flex items-center justify-center gap-2 py-3 rounded-xl font-bold text-sm text-white shadow-lg transition-all hover:scale-[1.01] active:scale-[0.99] disabled:opacity-50 disabled:cursor-not-allowed ${
              initialData
                ? "bg-gradient-to-r from-amber-600 to-orange-600 hover:shadow-amber-500/20"
                : "bg-gradient-to-r from-violet-600 to-indigo-600 hover:shadow-violet-500/20"
            }`}
          >
            {loading ? (
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : (
              <>
                {initialData ? "Update Post" : "Publish Content"}
                <Send size={14} className="group-hover:translate-x-1 transition-transform" />
              </>
            )}
          </button>
        </div>
      </form>
    </motion.div>
  );
}
